// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3620.FRC36202013Doug1;
    
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSubsystemPrimaryLeft;
    public static SpeedController driveSubsystemPrimaryRight;
    public static RobotDrive driveSubsystemPrimaryDrive;
    public static SpeedController driveSubsystemTurboLeft;
    public static SpeedController driveSubsystemTurboRight;
    public static RobotDrive driveSubsystemTurboDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSubsystemPrimaryLeft = new Victor(1, 1);
	LiveWindow.addActuator("DriveSubsystem", "PrimaryLeft", (Victor) driveSubsystemPrimaryLeft);
        
        driveSubsystemPrimaryRight = new Victor(1, 2);
	LiveWindow.addActuator("DriveSubsystem", "PrimaryRight", (Victor) driveSubsystemPrimaryRight);
        
        driveSubsystemPrimaryDrive = new RobotDrive(driveSubsystemPrimaryLeft, driveSubsystemPrimaryRight);
	
        driveSubsystemPrimaryDrive.setSafetyEnabled(true);
        driveSubsystemPrimaryDrive.setExpiration(0.1);
        driveSubsystemPrimaryDrive.setSensitivity(0.5);
        driveSubsystemPrimaryDrive.setMaxOutput(1.0);
        
        driveSubsystemTurboLeft = new Victor(1, 3);
	LiveWindow.addActuator("DriveSubsystem", "TurboLeft", (Victor) driveSubsystemTurboLeft);
        
        driveSubsystemTurboRight = new Victor(1, 4);
	LiveWindow.addActuator("DriveSubsystem", "TurboRight", (Victor) driveSubsystemTurboRight);
        
        driveSubsystemTurboDrive = new RobotDrive(driveSubsystemTurboLeft, driveSubsystemTurboRight);
	
        driveSubsystemTurboDrive.setSafetyEnabled(true);
        driveSubsystemTurboDrive.setExpiration(0.1);
        driveSubsystemTurboDrive.setSensitivity(0.5);
        driveSubsystemTurboDrive.setMaxOutput(1.0);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
