// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc3620.FRC36202013RobotRedo.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.PrintCommand;
import org.usfirst.frc3620.FRC36202013RobotRedo.Robot;

/**
 *
 */
public class  AutonomousBoxCommand extends CommandGroup {
    public AutonomousBoxCommand() {
        addSequential(new DriveMoveInLineCommand(1.0));
        addSequential(new PrintCommand("leg done"));
        addSequential(new DriveTurnInPlaceCommand(90.0));
        addSequential(new PrintCommand("turn done"));
        addSequential(new DriveMoveInLineCommand(1.0));
        addSequential(new PrintCommand("leg done"));
        addSequential(new DriveTurnInPlaceCommand(90.0));
        addSequential(new PrintCommand("turn done"));
        addSequential(new DriveMoveInLineCommand(1.0));
        addSequential(new PrintCommand("leg done"));
        addSequential(new DriveTurnInPlaceCommand(90.0));
        addSequential(new PrintCommand("turn done"));
        addSequential(new DriveMoveInLineCommand(1.0));
        addSequential(new PrintCommand("leg done"));
        addSequential(new DriveTurnInPlaceCommand(90.0));
        addSequential(new PrintCommand("all done"));
    }

}
