// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3620.FRC36202013RobotRedo.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3620.FRC36202013RobotRedo.Robot;
import org.usfirst.frc3620.FRC36202013RobotRedo.subsystems.DriveSubsystem;
/**
 *
 */
public class  DriveTurnInPlaceCommand extends Command {
    DriveSubsystem driveSubsystem = Robot.driveSubsystem;
    
    long t0;
    
    private double howFar;

    public DriveTurnInPlaceCommand(double degrees) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveSubsystem);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
        howFar = degrees;
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        t0 = System.currentTimeMillis();
        driveSubsystem.resetGyro();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        double howFast = 0.4;
        if (howFar > 0) {
            // turn right
            //driveSubsystem.autonomousTankDrive(-howFast, howFast);
            driveSubsystem.autonomousDrive(0.5, -1.0);
        } else {
            // turn left
            //driveSubsystem.autonomousTankDrive(howFast, -howFast);
            driveSubsystem.autonomousDrive(0.5, 1.0);
        }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if (System.currentTimeMillis() - t0 > 3000) return true;

        if (howFar > 0) {
            return driveSubsystem.readGyro() > howFar;
        } else {
            return driveSubsystem.readGyro() < howFar;
        }
    }
    // Called once after isFinished returns true
    protected void end() {
        driveSubsystem.halt();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
